# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    #- name: Set jar version
    #  run: ???
    - name: Clean
      run: mvn clean --file my-app/pom.xml
    - name: Compile with Maven
      run: mvn -B compile --file my-app/pom.xml
    - name: Package with Maven
      run: mvn -B package --file my-app/pom.xml
    - uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - run: mkdir artifacts && cp my-app/target/*.jar artifacts
    - name: Copy to artifacts dir
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: artifacts
      
