# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      final_version: ${{ steps.jar_version.outputs.new_version }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Increment jar version
      id: jar_version
      run: |
        POM_DIR=my-app
        PREV_VERSION=$(cd $POM_DIR && mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        prev="$PREV_VERSION"
        parts=( ${prev//./ } )
        v_num=$((parts[2] + 1))
        CURR_VERSION="${parts[0]}.${parts[1]}.${v_num}"
        echo "project version will be incremented by 1. was: " $PREV_VERSION "now: " $CURR_VERSION
        mvn versions:set -DoldVersion="${PREV_VERSION}" -DnewVersion="${CURR_VERSION}" --file $POM_DIR/pom.xml
        echo ::set-output name=new_version::${CURR_VERSION}
    
    - name: Clean
      run: mvn clean --file my-app/pom.xml
    
    - name: Compile with Maven
      run: mvn -B compile --file my-app/pom.xml
    
    - name: Package with Maven
      run: mvn -B package --file my-app/pom.xml
    
    - name: Copy jar 
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - run: mkdir artifacts && cp my-app/target/*.jar artifacts
    
    - name: Copy to artifacts dir
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: artifacts
      
